### ISSUE TITLE
Empty fixed_var_list throws error

### ISSUE THREAD

**Issue by ykl7** [tnq177/nmt_xfer_related_low_resource#1]
During training, line 146 of ```nmt/model.py fixedvars attrgetter``` expects 1 argument but gets 0. Passing an empty list explicitly has no effect either.

**Comment by tnq177** [comment]
Hi @ykl7 , thanks for noticing. This probably occurred when I "cleaned" the codebase to publish on github. I just fixed it. Basically just checking if the ```fixed_var_list``` is non-empty, and if it's empty, don't modify ```tvars``` (trainable variable list).
