### ISSUE TITLE
TypeError: 'map' object is not subscriptable

### ISSUE THREAD

**Issue by Nidachuhan** [tnq177/nmt_xfer_related_low_resource#2]
I use your code but I face one error 
I use python 3.7 and tensorflow 1.5

for j in range(beam_size):
                # We always run first_step first so this step always reuse cell no matter what
                with tf.variable_scope(self.scope, reuse=True):
                    h_t, state = (self.cell(inp[j], states[j]))

                output, aligments = output_func(h_t)
                current_states.append(state)
                current_outputs.append(output)
                current_alignments.append(aligments)

  h_t, state = (self.cell(inp[j], states[j]))
TypeError: 'map' object is not subscriptable

**Comment by tnq177** [comment]
hi @Nidachuhan, as indicated in the readme, I tested  with Python 2.7.3 and Tensorflow 1.1 only. There could be a lot of changes in LSTM implementation from tf 1.1 to 1.5. I don't plan to maintain this repo either since I switched to Pytorch :).
